# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://relishapp.com/rspec/rspec-core/docs/configuration/zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end

  # Below are methods that simplify the testing process and condense regularly used 
  # actions for testing e.g. logging in as a user/admin, and turns it into a singular
  # method call that can be used in any other testing file provided that file has a
  # <require_relative '../spec_helper.rb'> at the top of it (minus the <>).
  def logout_user
    visit '/'
    click_on 'Logout'
  end
  
  def sign_in_user
    login_as(user)
    visit '/'
  end

  def sign_in_admin
    login_as(admin)
    visit '/'
  end

  def elective_as_admin
    sign_in_admin
    visit '/electives'
  end

  def visit_dashboard
    sign_in_admin
    click_on 'Admin Dashboard'
  end

  def create_user_account
    visit '/'
    click_on 'Login'
    click_on 'Sign up'
    fill_in  'user_email', with: "test@sheffield.ac.uk"
    fill_in  'user_password', with: "Password1!"
    fill_in  'user_password_confirmation', with: "Password1!"
    click_on  'Sign up'
  end

  def delete_account
    create_user_account
    visit '/users/edit'

    # Currently not working, have to add id tag to cancel account button
    within '.container-fluid' do
      click_on 'Cancel my account'
    end
    page.driver.browser.switch_to.alert.accept
  end

  def manual_sign_in_user
    visit '/'
    click_on 'Login'
    fill_in  'user_email', with: "my.email@sheffield.ac.uk"
    fill_in  'user_password', with: "Password123"
  end

  def create_new_elective
    visit '/search'
    click_on 'New Elective'
    fill_in 'elective_Title', with: "Test Elective"
    fill_in 'elective_Description', with: "Lorem ipsum delorum"
    fill_in 'elective_Speciality', with: "Research"
    check 'elective_Accomodation'
    check 'elective_WP_Support'
    fill_in 'elective_Type', with: "///"
    click_on 'Save'
  end

  def edit_elective
    fill_in 'elective_Title', with: "1234"
    fill_in 'elective_Description', with: "1234"
    fill_in 'elective_Speciality', with: "1234"
    uncheck 'elective_Accomodation'
    uncheck 'elective_WP_Support'
    fill_in 'elective_Type', with: "1234"
    click_on 'Save'
  end

  def signin_user_with_elective
    elective_as_admin
    create_new_elective
    logout_user
    sign_in_user
  end

  def submit_question
    fill_in 'question_title', with: 'Test Title'
    fill_in 'question_body', with: 'Test Body'
    click_on 'Create Question'
  end

  def submit_answer
    fill_in 'answer_body', with: 'Test Answer Body'
    click_on 'Submit Answer'
    logout_user
    visit '/'
  end

  def approve_question
    visit_dashboard
    click_link 'Approve'
    logout_user
    visit '/'
  end

  def deny_question
    visit_dashboard
    click_link 'Deny'
    logout_user
    visit '/'
  end

  def approve_answer
    visit_dashboard
    click_link 'Approve'
    logout_user
    visit '/'
  end

  def deny_answer
    visit_dashboard
    click_link 'Deny'
    logout_user
    visit '/'
  end

  def reload_page
    visit current_path
  end
end
